---
- name: Remove Grafana
  hosts: main
  become: yes

  tasks:
  - name: Removed apt key
    ansible.builtin.apt_key:
      url: https://apt.grafana.com/gpg.key
      id: B53AE77BADB630A683046005963FA27710458545
      state: absent
  - name: Remove Grafana repo from sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: absent
  - name: Ensure Grafana is stopped and disabled
    ansible.builtin.systemd_service:
      name: grafana-server
      enabled: false
      state: stopped
  - name: Remove Grafana
    ansible.builtin.apt:
      name: grafana
      state: absent
      